# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[â•­â”€](fg:#4a6a5a)\
[î‚²](fg:#1a2a2a)\
$os\
$username\
[î‚°](bg:#1a2a2a fg:#1a2a2a)\
$directory\
[î‚°](fg:#1a2a2a bg:#2a443a)\
$git_branch\
$git_status\
[î‚°](fg:#2a443a bg:#3a5a4a)\
$nodejs\
[î‚°](fg:#3a5a4a bg:#4a6a5a)\
$docker_context\
[î‚°](fg:#4a6a5a)\
$fill\
[î‚²](fg:#1a2a2a)\
$time\
[î‚°](fg:#1a2a2a)\
$line_break\
[â•°â”€](fg:#4a6a5a)\
$character
"""

# Disable the blank line at the start of the prompt
add_newline = false

[character]
success_symbol = "[â±](bold fg:#5faf5f)"
error_symbol = "[ğœ±º](bold fg:#e67e80)"
vimcmd_symbol = "[ğœ±¸](bold fg:#7fbbb3)"

[username]
show_always = true
style_user = "fg:#d3c6aa bg:#1a2a2a"
style_root = "fg:#e67e80 bg:#1a2a2a"
format = '[ $user ]($style)'
disabled = false

[os]
style = "fg:#d3c6aa bg:#1a2a2a"
format = "[ $symbol ]($style)"
disabled = false

[os.symbols]
Arch = "ó°£‡"
Ubuntu = "ó°•ˆ"
Macos = "ó°€µ"
Windows = "ó°²"

[directory]
style = "fg:#d3c6aa bg:#1a2a2a"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[git_branch]
symbol = "ï˜"
style = "fg:#1a2a2a bg:#2a443a"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#1a2a2a bg:#2a443a"
format = '[$all_status$ahead_behind ]($style)'
conflicted = "â€‹"
ahead = "â€‹"
behind = "â€‹"
diverged = "â€‹"
up_to_date = "â€‹"
untracked = "â€‹"
stashed = "â‰¡"
modified = "â€‹"
staged = "â€‹"
renamed = "â€‹"
deleted = "â€‹"

[nodejs]
symbol = "îœ˜"
style = "fg:#1a2a2a bg:#3a5a4a"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = "ïŒˆ"
style = "fg:#1a2a2a bg:#4a6a5a"
format = '[ $symbol $context ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:#d3c6aa bg:#1a2a2a"
format = '[ ïº $time ]($style)'

[fill]
symbol = " "
style = "fg:#2a3a3a"
